name: weather_app
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.7.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1

  # Networking & Location
  http: ^1.5.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Date and Time Formatting
  intl: ^0.20.2

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  fonts:
    - family: 'SFProDisplay'
      fonts:
        - asset: assets/font/SFPRODISPLAYREGULAR.otf
  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/components/
    - assets/icons/
